## Kuhnian paradigms and Normal Science

In the Structure of Scientific Revolutions, @Kuhn:1962 offers a generally descriptive account of how all sciences appear to have changed over time. To the extent that these changes can be construed in terms of developmental progress, they follow from motivations that appear common among scientific enterprises: to generate understanding of a wide range of phenomena and to provide increasingly specified guides for further scientific research. Kuhn illustrates this general trajectory by identifying two stages of development. 

The first of these stages is termed *pre-paradigm* and is marked by an absence of any unifying perspectives. At this stage, theories proliferate at the pace of observed effects, where these theories are little more than descriptions of a given phenomenon (e.g., when *X* is placed over a flame, *Y* occurs). Because these theories offer little regarding underlying mechanisms, they present no clear hypotheses beyond the replication of the original effect. They are essentially tautological, reflecting little in the way of general understanding of a phenomenon, and unable to produce novel predictions.

According to Kuhn, all scientific communities eventually acknowledge this limitation and gradually make their way to a standard phase of scientific inquiry. In the *Normal Science* phase, an underlying phenomenon is hypothesized to manifest in the various previously unrelated empirical phenomena (e.g., space-time or genes). This hypothesized unifying phenomenon lies at the core of a new paradigm, a broad nest of theoretical conceits that shape predictions for future observations. Increasingly specifying the nature of these conceits --- theory articulation ---  guides the identification of novel effects (rather than the generation of novel "theories") and subsequent research efforts. 

Kuhn's depiction of Normal Science progress does not rest on a particular epistemic school of thought [e.g., @Popper:1959]. Rather, paradigms are understood to facilitate progress by motivational means, insofar as they represent progress narratives that encourage scientists to predict and accumulate paradigm-verifying effects [rather than perseverate on potentially falsifying anomalies, Popper, 1959 – see also the positive heuristic, @Lakatos:1970]. 



The motivational and verificationist realities of Normal Science have fundamental implications for how the "null hypothesis" is interpreted, and whether or not it is "accepted." In a Normal Science setting, multiple explanatory paradigms offer competing accounts of demonstrated effects and differing predictions for what may be observed in the future. When hypotheses following from a given paradigm are not supported by the data, the null hypotheses can be readily accepted, as the observed "null" effect may offer support for a competing paradigm and represent an additional element of accumulated knowledge. Alternatively, Normal Science may be dominated by a single, broad explanatory paradigm that can account for the bulk of prior findings, and continues to make successful predictions for demonstrable effects. In this setting, scientists may be extremely reluctant to accept a null hypothesis that would challenge a paradigm that must be correct, insofar as it has been otherwise verified in dozens (hundreds) of prior experiments, and because there are no other options, meaning that the acceptance of the null could lead to a scientific crisis. 

We discuss three examples of null effects demonstrated within the paradigmatic context of Normal Science. The first and the third are from nineteenth and twenty-first century physics, respectively; the second, from nineteenth- and twentieth-century biology. In each case, we emphasize the relationship of the statistical inference for or against a null hypothesis in the context of the relevant paradigm. Following this, we contrast the situation in Normal Science with that in present-day psychology.




